"""
PotholeWatch v3 — PDF Report Generator
Builds a complete A4 PDF report in memory using ReportLab.
"""
import io
import requests
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image as RLImage, PageBreak
)
from reportlab.lib.utils import ImageReader

# Severity colors in ReportLab format
SEVERITY_COLORS = {
    "high":   colors.HexColor("#dc3545"),
    "medium": colors.HexColor("#fd7e14"),
    "low":    colors.HexColor("#28a745"),
}

DARK_HEADER = colors.HexColor("#2c3e50")
LIGHT_GRAY  = colors.HexColor("#f8f9fa")
MID_GRAY    = colors.HexColor("#dee2e6")


def _add_page_number(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.gray)
    canvas.drawRightString(A4[0] - 2 * cm, 1.5 * cm, f"Page {doc.page}")
    canvas.drawString(2 * cm, 1.5 * cm, "Generated by PotholeWatch. This report is auto-generated.")
    canvas.restoreState()


def generate_pdf_report(
    detections: list,
    stats: dict,
    date_from: str,
    date_to: str,
    generated_by_name: str,
) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2.5 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    story  = []

    # ── 1. HEADER ─────────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=22,
        textColor=DARK_HEADER,
        spaceAfter=6,
    )
    sub_style = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.gray,
        spaceAfter=4,
    )
    info_style = ParagraphStyle(
        "Info",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=2,
    )

    story.append(Paragraph("🚧 Road Pothole Detection Report", title_style))
    story.append(Paragraph("PotholeWatch System — Automated Report", sub_style))
    story.append(Paragraph(f"Report Period: {date_from} to {date_to}", info_style))
    story.append(Paragraph(f"Generated by: {generated_by_name}", info_style))
    story.append(Paragraph(f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", info_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=2, color=DARK_HEADER))
    story.append(Spacer(1, 0.5 * cm))

    # ── 2. EXECUTIVE SUMMARY TABLE ─────────────────────────────────────────────
    summary_data = [
        ["Metric", "Value"],
        ["Total Detections", str(stats.get("total", 0))],
        ["High Severity", str(stats.get("high", 0))],
        ["Medium Severity", str(stats.get("medium", 0))],
        ["Low Severity", str(stats.get("low", 0))],
        ["Average Confidence", f"{stats.get('avg_confidence', 0) * 100:.1f}%"],
        ["GPS-Tagged", str(stats.get("with_gps", 0))],
        ["Report Period", f"{date_from} → {date_to}"],
    ]

    summary_table = Table(summary_data, colWidths=[9 * cm, 8 * cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), DARK_HEADER),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 11),
        ("ALIGN",         (0, 0), (-1, -1), "LEFT"),
        ("FONTSIZE",      (0, 1), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [LIGHT_GRAY, colors.white]),
        ("GRID",          (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        # Severity cell colors
        ("TEXTCOLOR",     (1, 2), (1, 2), SEVERITY_COLORS["high"]),
        ("FONTNAME",      (1, 2), (1, 2), "Helvetica-Bold"),
        ("TEXTCOLOR",     (1, 3), (1, 3), SEVERITY_COLORS["medium"]),
        ("TEXTCOLOR",     (1, 4), (1, 4), SEVERITY_COLORS["low"]),
    ]))

    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(Spacer(1, 0.2 * cm))
    story.append(summary_table)
    story.append(Spacer(1, 0.6 * cm))

    # ── 3. DETECTIONS TABLE ────────────────────────────────────────────────────
    story.append(Paragraph("Detection Records", styles["Heading2"]))
    story.append(Spacer(1, 0.2 * cm))

    max_rows = 50
    shown = detections[:max_rows]
    if len(detections) > max_rows:
        story.append(Paragraph(
            f"<i>Showing {max_rows} of {len(detections)} detections.</i>",
            ParagraphStyle("Note", parent=styles["Normal"], textColor=colors.gray, fontSize=9)
        ))

    det_data = [["#", "Date & Time", "Severity", "Confidence", "Input Type", "GPS Coords"]]
    for i, d in enumerate(shown, 1):
        dt_raw = d.get("created_at", "")
        dt_fmt = dt_raw[:19].replace("T", " ") if dt_raw else "—"
        lat = d.get("latitude")
        lng = d.get("longitude")
        gps = f"{lat:.4f}, {lng:.4f}" if lat and lng else "—"
        det_data.append([
            str(i),
            dt_fmt,
            d.get("severity", "").upper(),
            f"{d.get('confidence', 0) * 100:.1f}%",
            d.get("input_type", "—"),
            gps,
        ])

    det_table = Table(
        det_data,
        colWidths=[1 * cm, 4.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 4 * cm]
    )
    row_colors = []
    for i, d in enumerate(shown, 1):
        sev = d.get("severity", "low")
        row_colors.append(("TEXTCOLOR", (2, i), (2, i), SEVERITY_COLORS.get(sev, colors.black)))
        row_colors.append(("FONTNAME",  (2, i), (2, i), "Helvetica-Bold"))

    det_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), DARK_HEADER),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
        ("GRID",          (0, 0), (-1, -1), 0.3, MID_GRAY),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        *row_colors,
    ]))
    story.append(det_table)
    story.append(Spacer(1, 0.8 * cm))

    # ── 4. DETECTION IMAGES GRID ───────────────────────────────────────────────
    image_detections = [d for d in detections if d.get("image_url")][:12]
    if image_detections:
        story.append(Paragraph("Detection Thumbnails", styles["Heading2"]))
        story.append(Spacer(1, 0.2 * cm))
        grid_cells = []
        for d in image_detections:
            try:
                resp = requests.get(d["image_url"], timeout=5)
                resp.raise_for_status()
                img_buf = io.BytesIO(resp.content)
                rl_img = RLImage(img_buf, width=5.5 * cm, height=4 * cm)
                sev = d.get("severity", "—").upper()
                conf = f"{d.get('confidence', 0) * 100:.1f}%"
                dt   = d.get("created_at", "")[:10]
                caption = Paragraph(
                    f"<b>{sev}</b> | {conf}<br/>{dt}",
                    ParagraphStyle("Cap", parent=styles["Normal"], fontSize=7, alignment=TA_CENTER)
                )
                grid_cells.append([rl_img, caption])
            except Exception:
                grid_cells.append(["(image unavailable)", ""])

        # 3-column grid
        rows = []
        row  = []
        for cell in grid_cells:
            row.append(cell)
            if len(row) == 3:
                rows.append(row)
                row = []
        if row:
            while len(row) < 3:
                row.append(["", ""])
            rows.append(row)

        for row in rows:
            flat = [item for cell in row for item in cell]
            grid_table = Table(
                [flat[:3], flat[3:]],
                colWidths=[6 * cm, 6 * cm, 6 * cm]
            )
            grid_table.setStyle(TableStyle([
                ("ALIGN",  (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(grid_table)
            story.append(Spacer(1, 0.3 * cm))

    # Build
    doc.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)
    buffer.seek(0)
    return buffer
